helper_dictionary = {
    'Kyiv': 'Ukraine',
    'Moscow': 'Russia',
    'St Petersburg': 'Russia',
    'Lviv': 'Ukraine',
    'Kharkiv': 'Ukraine',
    'Odessa': 'Ukraine',
    'Mariupol': 'Ukraine',
    'Donetsk': 'Ukraine',
    'Luhansk': 'Ukraine',
    'Sevastopol': 'Ukraine',
    'Crimea': 'Ukraine',
    'Zaporizhzhia': 'Ukraine',
    'Dnipro': 'Ukraine',
    'Belgorod': 'Russia',
    'Rostov-on-Don': 'Russia',
    'Kursk': 'Russia',
    'Bryansk': 'Russia',
    'Voronezh': 'Russia',
    'Sochi': 'Russia',
    'Krasnodar': 'Russia',
    'Bakhmut': 'Ukraine',
    'Avdiivka': 'Ukraine',
    'Kherson': 'Ukraine',
    'Mykolaiv': 'Ukraine',
    'Chernihiv': 'Ukraine',
    'Sumy': 'Ukraine',
    'Vinnytsya': 'Ukraine',
    'Poltava': 'Ukraine',
    'Cherkasy': 'Ukraine',
    'Zhytomyr': 'Ukraine',
    'Rivne': 'Ukraine',
    'Lutsk': 'Ukraine',
    'Ternopil': 'Ukraine',
    'Ivano-Frankivsk': 'Ukraine',
    'Uzhhorod': 'Ukraine',
    'Chernivtsi': 'Ukraine',
    'Khmelnytskyi': 'Ukraine',
    'Kropyvnytskyi': 'Ukraine',
    'Slovyansk': 'Ukraine',
    'Kramatorsk': 'Ukraine',
    'Yekaterinburg': 'Russia',
    'Novosibirsk': 'Russia',
    'Kazan': 'Russia',
    'Nizhny Novgorod': 'Russia',
    'Chelyabinsk': 'Russia',
    'Samara': 'Russia',
    'Omsk': 'Russia',
    'Ufa': 'Russia',
    'Perm': 'Russia',
    'Volgograd': 'Russia',
    'Irkutsk': 'Russia',
    'Tyumen': 'Russia',
    'Makhachkala': 'Russia',
    'Grozny': 'Russia',
    'Vladivostok': 'Russia',
    'Ukraine, Kyiv': 'Ukraine',
    'Mülheim an der Ruhr, Germany': 'Germany',
    'Україна': 'Ukraine',
    'Ukraine': 'Ukraine',
    'Warsaw': 'Poland',
    'Київ': 'Ukraine',
    'Украина': 'Ukraine',
    'Київ, вул. Є. Чикаленка, б. 36': 'Ukraine',
    'Крим, Україна': 'Ukraine',
    'Crimea. Ukraine.': 'Ukraine',
    'Kyiv, Ukraine': 'Ukraine',
    'місто За порогами Дніпра': 'Ukraine',
    'Вінниця': 'Ukraine',
    'Ukraina': 'Ukraine',
    'Київ, ЄвроМайдан': 'Ukraine',
    'Киев': 'Ukraine',
    'м. Київ , вул. Петра Нестерова, 4': 'Ukraine',
    'Студентська 12А, Київ, Україна': 'Ukraine',
    'м. Київ': 'Ukraine',
    'Україна Київ': 'Ukraine',
    'Україна, Київ': 'Ukraine',
    'вул. Стрілецька, 105 Vinnytsia': 'Ukraine',
    'Ukraine, Kyiv; Georgia,Tbilisi': 'Ukraine/Georgia',
    'Київ,Україна  Kyiv,Ukraine': 'Ukraine',
    'Маріуполь': 'Ukraine',
    'Я з України!': 'Ukraine',
    'Lviv, Ukraine': 'Ukraine',
    'Никополь Украина': 'Ukraine',
    'Washington, D.C.': 'United States',
    'Київ, пр. Берестейський, 10': 'Ukraine',
    'Київ, Україна': 'Ukraine',
    'Харків': 'Ukraine',
    'Київ. Україна': 'Ukraine',
    'вул. Прорізна, 2': 'Ukraine',
    'м. Київ, вул. Тургенівська 25': 'Ukraine',
    'Одеса': 'Ukraine',
    'Україна, Київ.': 'Ukraine',
    'по всем вопросам +380503535031': 'Ukraine',
    'ДПСУ': 'Ukraine',
    'Kyiv, Ukraina': 'Ukraine',
    'м. Київ, Львівська пл. 8, 04053': 'Ukraine',
    'Чернігів': 'Ukraine',
    'Slovak Republic': 'Slovakia',
    'Київ, вул. Володимирська, 33': 'Ukraine',
    'Україна мати!': 'Ukraine',
    'Liberal, KS': 'United States',
    'кіт десь поруч': 'Unknown',
    'м. Київ, вул. Хрещатик, 6': 'Ukraine',
    'Los Angeles, CA': 'United States',
    'Kyiv, UA': 'Ukraine',
    'Ми переможемо!': 'Ukraine',
    'Україна (скрізь)': 'Ukraine',
    'Ternopil, Ukraine': 'Ukraine',
    'Україна, Донецьк': 'Ukraine',
    'Ukraine, Kiev': 'Ukraine',
    'Green Family Ltd, Кіпр': 'Cyprus',
    'украина': 'Ukraine',
    'Ukraine - UK': 'Ukraine/UK',
    'Україна, Київ, вул. Федора Ернста, 3, 03048': 'Ukraine',
    'Kiev, Ukraine': 'Ukraine',
    'tierra di Kolomyya': 'Ukraine',
    'Kyiv, UKRAINE': 'Ukraine',
    'Киев - городов ваших мать': 'Ukraine',
    'Ukraine / Europe': 'Ukraine',
    'Полтава': 'Ukraine',
    'Франківськ/Косів/Соколівка': 'Ukraine',
    'Ukraine, Odessa': 'Ukraine',
    'Tallinn, Estonia': 'Estonia',
    'UA': 'Ukraine',
    'Rīga, Latvia': 'Latvia',
    'moscow': 'Russia',
    'Moscow, Russia': 'Russia',
    'Russia. Moscow': 'Russia',
    'IF': 'Ireland',
    'Europe': 'Europe',
    'аня злюка бобер': 'Unknown',
    'Гватемала': 'Guatemala',
    'Житомир, Украина': 'Ukraine',
    'Бонжур бля сильвупле': 'France',
    'Kiev': 'Ukraine',
    'Керчь': 'Ukraine',
    'київ': 'Ukraine',
    'Odessa -Ukraine': 'Ukraine',
    'planet Earth': 'Earth',
    'Israel': 'Israel',
    'Germany': 'Germany',
    'Космическое пространство': 'Space',
    'Луцьк/Київ': 'Ukraine',
    'Львів': 'Ukraine',
    'Москва': 'Russia',
    'Antalya, Turkey': 'Turkey',
    'Москва-Лондон': 'Russia/UK',
    'chicago and everywhere': 'United States',
    'Рідні дєбуни': 'Unknown',
    'РОЛЕВАЯ ПО ВСЁ РАДИ ИГРЫ': 'Unknown',
    'Boston': 'United States',
    'Copenhagen.': 'Denmark',
    'Россия': 'Russia',
    'Odesa': 'Ukraine',
    'Ukraine, Ternopil': 'Ukraine',
    'Рыбница': 'Moldova',
    'Vilnius, Lithuania': 'Lithuania',
    'Рязань. Кремль 15': 'Russia',
    'Саранск': 'Russia',
    'Dnipro, Ukraine': 'Ukraine',
    'dm for commission info': 'Unknown',
    'Plovidv, България': 'Bulgaria',
    'Степ': 'Russia',
    'Таганрог, Россия': 'Russia',
    'Valhalla': 'Unknown',
    'Теребовлянський Замок': 'Ukraine',
    'St. Petersburg': 'Russia',
    'Turkey': 'Turkey',
    'Łódź, Polska': 'Poland',
    'Украина, Донецк': 'Ukraine',
    'Украина, Киев': 'Ukraine',
    'SF Bay': 'United States',
    'Ukraine; Mariupol': 'Ukraine',
    'kyiv, ukraine': 'Ukraine',
    'Cherkasy, Ukraine': 'Ukraine',
    'Sweden': 'Sweden',
    'Україна, Одеса': 'Ukraine',
    'Ukraine, Kharkiv': 'Ukraine',
    'Odessa,Ukraina': 'Ukraine',
    'Україна, Стрий, Київ': 'Ukraine',
    'что я делал в Муравленко?': 'Russia',
    'Москва, Россия': 'Russia',
    'israel   lod    t.me/numerolog': 'Israel',
    '|': 'Unknown',
    'Riverdale': 'Canada',
    'Zhyloy 12, Nur-Sultan': 'Kazakhstan',
    'Санкт-Петербург, Россия': 'Russia',
    'Ukraine, Liviv': 'Ukraine',
    'Belarus, Minsk': 'Belarus',
    'Troyes': 'France',
    'Santa Clara, CA': 'United States',
    'Россия, г.Владимир': 'Russia',
    'Alchevsk - Lviv': 'Ukraine',
    'Це Бориспіль': 'Ukraine',
    'Riga, Latvia': 'Latvia',
    'Melitopol': 'Ukraine',
    'Saint Petersburg, Russia': 'Russia',
    'Україна Київ 03190 а/с № 15': 'Ukraine',
    'Denver, CO': 'United States',
    '#CrimeaIsUkraine': 'Ukraine',
    'АС Киев, ул.Симона Петлюры 32': 'Ukraine',
    'Krakow, Poland': 'Poland',
    'Riga': 'Latvia',
    'Amersfort': 'Netherlands',
    'Earth planet': 'Earth',
    'New York, NY': 'United States',
    'Gliwice, Polska': 'Poland',
    'Nîmes': 'France',
    'Deutschland': 'Germany',
    'парні з пнем та пнем колодою': 'Unknown',
    'Kijów-Wrocław': 'Poland',
    'Старый оскол': 'Russia',
    'Malmo, Sweden': 'Sweden',
    'Одесса, Украина': 'Ukraine',
    'Москва, Россияи': 'Russia',
    'Sienna, Tuscany': 'Italy',
    'Uruk': 'Iraq',
    'Україна /Ukrain': 'Ukraine',
    'Magic World': 'Unknown',
    'Lausanne, Switzerland': 'Switzerland',
    'эээ': 'Unknown',
    'New York, NY, USA': 'United States',
    'Paris': 'France',
    'Italy': 'Italy',
    'Новосибирск': 'Russia',
    'Читайте тут': 'Unknown',
    'Russia': 'Russia',
    'Space void': 'Space',
    'Vancouver, British Columbia': 'Canada',
    'Ukraine, Dnipro': 'Ukraine',
    'San Francisco, CA': 'United States',
    'Kyiv, str. E. Chikalenko, b. 36': 'Ukraine',
    'Crimea, Ukraine': 'none',
    'the city Beyond the rapids of the Dnipro': 'Ukraine',
    'Vinnytsia': 'Ukraine',
    'Kyiv, EuroMaidan': 'Ukraine',
    'Kyiv, st. Petra Nesterova, 4': 'Ukraine',
    'Studentska 12A, Kyiv, Ukraine': 'Ukraine',
    'Ukraine Kyiv': 'Ukraine',
    'St. Striletska, 105 Vinnytsia': 'Ukraine',
    'Ukraine, Kyiv; Georgia, Tbilisi': 'Ukraine \nGeorgia',
    'Kyiv, Ukraine Kyiv, Ukraine': 'Ukraine',
    "I'm from Ukraine!": 'Ukraine.',
    'Nikopol Ukraine': 'Ukraine',
    'Kyiv, 10 Beresteyskyi Ave': 'Ukraine',
    'Kyiv. Ukraine': 'Ukraine',
    'St. Prorizna, 2': 'none',
    'Kyiv, str. Turgenivska 25': 'Ukraine',
    'Ukraine, Kyiv.': 'Ukraine.',
    'for all questions +380503535031': 'Ukraine',
    'DPSU': 'none',
    'Kyiv, Lvivska Square 8, 04053': 'Ukraine',
    'Kyiv, str. Volodymyrska, 33': 'Ukraine',
    'Mother Ukraine!': 'Ukraine',
    'the cat is somewhere nearby': 'none',
    'Kyiv, str. Khreschatyk, 6': 'Ukraine',
    'We will win!': 'none',
    'Ukraine (everywhere)': 'Ukraine',
    'Ukraine, Donetsk': 'Ukraine',
    'Green Family Ltd, Cyprus': 'Cyprus',
    'Ukraine, Kyiv, str. Fedora Ernst, 3, 03048': 'Ukraine',
    'chalker': 'none',
    'Kyiv is the mother of your cities': 'Ukraine',
    'Frankivsk/Kosiv/Sokolovka': 'Ukraine',
    'Anya is an angry beaver': 'none',
    'Guatemala': 'Guatemala',
    'Zhytomyr, Ukraine': 'Ukraine',
    'Bonjour fucking silvupple': 'none',
    'Kerch': 'Russia',
    'Odessa - Ukraine': 'Ukraine',
    'Outer space': 'none',
    'Lutsk/Kyiv': 'Ukraine',
    'Moscow-London': 'none',
    'Native debuns': 'none',
    'ROLE-PLAYING ALL FOR THE SAKE OF THE GAME': 'none',
    'Rybnitsa': 'Moldova',
    'Ryazan. Kremlin 15': 'Russia',
    'Saransk': 'Russia',
    'Plovidv, Bulgaria': 'Bulgaria',
    'Steppe': 'none',
    'Taganrog, Russia': 'Russia',
    'Terebovlyan Castle': 'Ukraine',
    'Lodz, Poland': 'Poland',
    'Ukraine, Odesa': 'Ukraine',
    'Odessa, Ukraine': 'Ukraine',
    'Ukraine, Stryi, Kyiv': 'Ukraine',
    'what was I doing in Muravlenko?': 'Russia',
    'israel lot t.me/numerologist': 'Israel',
    'St. Petersburg, Russia': 'Russia',
    'Russia, Vladimir': 'Russia',
    'This is Boryspil': 'Ukraine',
    'Ukraine Kyiv 03190 a/s No. 15': 'Ukraine',
    'AS Kyiv, 32 Simona Petlyuri str': 'Ukraine',
    'Gliwice, Poland': 'Poland',
    'Nimes': 'France',
    'pairs with a stump and a stump log': 'none',
    'Kyiv-Wrocław': 'Poland',
    'Stary Oskol': 'Russia',
    'Ukraine / Ukraine': 'Ukraine',
    'eh': 'none',
    'Read here': 'none'
}
